// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDgKGM-g5gWbjJdvSJlyURioPH4Jiwr_E',
    appId: '1:901132635547:web:28a12d0a4ca403739d253e',
    messagingSenderId: '901132635547',
    projectId: 'reusea-9dd1b',
    authDomain: 'reusea-9dd1b.firebaseapp.com',
    storageBucket: 'reusea-9dd1b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeqSJIxpUNgIjJUY7CfA2jSIypzh0l8Gk',
    appId: '1:901132635547:android:2e08183ad05f2e039d253e',
    messagingSenderId: '901132635547',
    projectId: 'reusea-9dd1b',
    storageBucket: 'reusea-9dd1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUc0RUL3y0Eu18HrkqPivqM2PQ9lPwelc',
    appId: '1:901132635547:ios:623bf10e732d95e49d253e',
    messagingSenderId: '901132635547',
    projectId: 'reusea-9dd1b',
    storageBucket: 'reusea-9dd1b.firebasestorage.app',
    iosBundleId: 'com.example.reusea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUc0RUL3y0Eu18HrkqPivqM2PQ9lPwelc',
    appId: '1:901132635547:ios:623bf10e732d95e49d253e',
    messagingSenderId: '901132635547',
    projectId: 'reusea-9dd1b',
    storageBucket: 'reusea-9dd1b.firebasestorage.app',
    iosBundleId: 'com.example.reusea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDgKGM-g5gWbjJdvSJlyURioPH4Jiwr_E',
    appId: '1:901132635547:web:4452aa0315b47ed49d253e',
    messagingSenderId: '901132635547',
    projectId: 'reusea-9dd1b',
    authDomain: 'reusea-9dd1b.firebaseapp.com',
    storageBucket: 'reusea-9dd1b.firebasestorage.app',
  );
}
